export const chessPiecesData = [
    {
        colour: "white",
        pawns: [
            {
                id: 1,
                position: { x: 0, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 2,
                position: { x: 1, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 3,
                position: { x: 2, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 4,
                position: { x: 3, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 5,
                position: { x: 4, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 6,
                position: { x: 5, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 7,
                position: { x: 6, y: 1 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 8,
                position: { x: 7, y: 1 },
                movement: 1,
                isQueen: false,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #ffc1c1;"></i>`,
            },
        ],
        knights: [
            {
                id: 1,
                position: { x: 1, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-knight piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 2,
                position: { x: 6, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-knight piece" style="color: #ffc1c1;"></i>`,
            },
        ],
        bishops: [
            {
                id: 1,
                position: { x: 2, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-bishop piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 2,
                position: { x: 5, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-bishop piece" style="color: #ffc1c1;"></i>`,
            },
        ],
        rooks: [
            {
                id: 1,
                position: { x: 0, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-rook piece" style="color: #ffc1c1;"></i>`,
            },
            {
                id: 2,
                position: { x: 7, y: 0 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-rook piece" style="color: #ffc1c1;"></i>`,
            },
        ],
        queen: {
            id: 1,
            position: { x: 3, y: 0 },
            movement: {},
            isAlive: true,
            display: `<i class="fa-solid fa-chess-queen piece" style="color: #ffc1c1;"></i>`,
        },

        king: {
            id: 1,
            position: { x: 4, y: 0 },
            movement: 1,
            isAlive: true,
            display: `<i class="fa-solid fa-chess-king piece" style="color: #ffc1c1;"></i>`,
        },
    },
    {
        colour: "black",
        pawns: [
            {
                id: 1,
                position: { x: 0, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 2,
                position: { x: 1, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 3,
                position: { x: 2, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 4,
                position: { x: 3, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 5,
                position: { x: 4, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 6,
                position: { x: 5, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 7,
                position: { x: 6, y: 6 },
                movement: 1,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
            {
                id: 8,
                position: { x: 7, y: 6 },
                movement: 1,
                isQueen: false,
                isAlive: true,
                display: `<i class="fa-solid fa-chess-pawn piece" style="color: #125c28;"></i>`,
            },
        ],
        knights: [
            {
                id: 1,
                position: { x: 1, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-knight piece" style="color: #125c28;"></i>`,
            },
            {
                id: 2,
                position: { x: 6, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-knight piece" style="color: #125c28;"></i>`,
            },
        ],
        bishops: [
            {
                id: 1,
                position: { x: 2, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-bishop piece" style="color: #125c28;"></i>`,
            },
            {
                id: 2,
                position: { x: 5, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-bishop piece" style="color: #125c28;"></i>`,
            },
        ],
        rooks: [
            {
                id: 1,
                position: { x: 0, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-rook piece" style="color: #125c28;"></i>`,
            },
            {
                id: 2,
                position: { x: 7, y: 7 },
                movement: {},
                isAlive: true,
                display: `<i class="fa-solid fa-chess-rook piece" style="color: #125c28;"></i>`,
            },
        ],
        queen: {
            id: 1,
            position: { x: 3, y: 7 },
            movement: {},
            isAlive: true,
            display: `<i class="fa-solid fa-chess-queen piece" style="color: #125c28;"></i>`,
        },
        king: {
            id: 1,
            position: { x: 4, y: 7 },
            movement: 1,
            isAlive: true,
            display: `<i class="fa-solid fa-chess-king piece" style="color: #125c28;"></i>`,
        },
    },
];
